[project]
name = "gum-prime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents==0.2.9",
    "verifiers[all]>=0.1.3",
]

[tool.uv.sources]
verifiers = { git = "https://github.com/willccbb/verifiers.git" }
