max_steps = 200
batch_size = 8
micro_batch_size = 1
seq_len = 1024
rollouts_per_example = 8
mask_truncated_completions = false

[model]
name = "Qwen/Qwen2.5-1.5B-Instruct"

[sampling]
max_tokens = 512

[environment]
id = "haiku"

[environment.args]
use_thinking = true
min_length = 256
max_length = 512

[ckpt]
interval = 25
